---
title: "Étale Morphisms"
subtitle: ""
description: "Equivalent characterizations of étale morphisms through smoothness, flatness, unramifiedness, and tangent spaces."
order: 70
---

In this section, we want to explain the equivalent definitions of \etale morphsim.

First, as we all known, etale morphism could be defined by smooth morphism of relative dimension $0$. Thus, it is easy to find that for any smooth morphism of relative dimension $n$, locally factors as $U\to \mathbb A^n_V\to V$ where the first one is \etale and the second one is the structure morphism.

After we establish the fact that we can characterize smooth morphisms by the sheaf of differentials in [Smooth Morphisms Again](smooth-morphisms-again.qmd), we could deduce that \etale morphisms are the morphisms that are smooth and unramified. Besides, we also know that we could redefine smooth morphism by requiring flatness, locally finitely presented and $n$-dimensional smoothness of the fibres. Due to the fact that $n=0$ and the criterion for unramifiedness by checking fibres, we could then redefine \etale morphism by requiring only flatness, unramifiedness and locally finitely presentedness. 

For varieties over an algebraically closed field, we know that unramifiedness of morphisms is equivalent to the everywhere-injectness of morphisms induced between the tangent spaces on closed points; and smoothness on a nonsingular point is equivalent to the injectness of morphism induced between the cotangent spaces. For the respect results, see [The Sheaf of Differentials and Unramified Morphisms](unramified-morphisms.qmd) and [Smooth Morphisms Again](smooth-morphisms-again.qmd). Therefore, for nonsingular varieties, etale morphisms are exactly the morphisms inducing bijection between (co)tangent spaces on closed points. (Note that closed points are dense and nsmooth locus is open for varieties.)

For other famous propeties of \etale morphisms, from the flatness follows the openness, from the unramifiedness follows the fact that the induced diagonal morphism is an open immersion.

standard \etale and local model.

finite \etale and covering space.

