---
title: "Étale Morphisms"
subtitle: ""
description: "Equivalent definitions of étale morphisms and intuition for the roles of flatness and unramifiedness."
order: 10
start-page: "etale morphism/definitions.qmd"
toc: false
listing:
  id: topic-pages
  contents: "*.qmd"
  template: "../_templates/topic-pages.ejs.md"
  fields: [title, description, order]
  sort: "order asc"
  sort-ui: false
  filter-ui: false
---
::: {.callout-note title="Cite"}
"An étale morphism is the analogue in algebraic geometry of a local isomorphism of manifolds in differential geometry, a covering of Riemann surfaces with no branch points in complex analysis, and an unramiﬁed extension in algebraic number theory."--Milne.
:::

Since the author, I, hasn't learned flat morphisms and unramified morphisms seriously yet, but already has a basic understanding of the \etale site and \etale cohomology, which means that the author is familiar to some basic properties of \etale morphisms and use it. Our main goal in this chapter is to understand the various equivalent definitions of étale morphisms and to get some intuition for what they are analog to. One of the purpose of this chapter is to figure out which property of \etale morphisms comes from the flatness and which property comes from the unramifiedness. The author will try to understand the definition of étale morphisms in a more intuitive way, and then try to understand the properties of étale morphisms from the perspective of flatness and unramifiedness.

## Contents

::: {#topic-pages}
:::
